/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package croftventory.Types;

import javafx.beans.property.*;
import java.time.LocalDate;

/**
 *
 * Defines the Booking object
 * 
 * @author kamron
 * 
 */

public class Booking {
    // Properties
    // These are used over variables as they can utilize events
    // Additionally they are useful for the TableView
    private SimpleStringProperty StrStudent = new SimpleStringProperty();
    private SimpleLongProperty LngDevice = new SimpleLongProperty();
    private SimpleIntegerProperty IntQuantity = new SimpleIntegerProperty();
    private SimpleObjectProperty<LocalDate> DateLent = new SimpleObjectProperty<>();
    private SimpleObjectProperty<LocalDate> DateDue = new SimpleObjectProperty<>();
    private SimpleBooleanProperty BoolReturned = new SimpleBooleanProperty();
    private SimpleLongProperty LngID = new SimpleLongProperty();
    
    // Initialiser
    // Uses polymorphisem to handle storing and retrieving data from database
    // As ID is generated by database itself (for security reasons)
    public Booking(String student, long device, int quantity, LocalDate lent, LocalDate due, boolean returned, long ID) {
        this.StrStudent.set(student);
        this.LngDevice.set(device);
        this.IntQuantity.set(quantity);
        this.DateLent.set(lent);
        this.DateDue.set(due);
        this.BoolReturned.set(returned);
        this.LngID.set(ID);
    }
    
    public Booking(String student, long device, int quantity, LocalDate lent, LocalDate due, boolean returned) {
        this.StrStudent.set(student);
        this.LngDevice.set(device);
        this.IntQuantity.set(quantity);
        this.DateLent.set(lent);
        this.DateDue.set(due);
        this.BoolReturned.set(returned);
    }
    
    // Getters
    // Getters which return properties
    // Useful for UI elements
    public StringProperty studentProperty() { return StrStudent; }
    public LongProperty deviceProperty() { return LngDevice; }
    public IntegerProperty quantityProperty() { return IntQuantity; }
    public ObjectProperty<LocalDate> lentProperty() { return DateLent; }
    public ObjectProperty<LocalDate> dueProperty() { return DateDue; }
    public BooleanProperty returnedProperty() { return BoolReturned; }
    public LongProperty IDProperty() { return LngID; }
    
    //Getters for variables
    //Useful for validation and other purposes
    public String getStrStudent() { return StrStudent.get(); }
    public Long getLngDevice() { return LngDevice.get(); }
    public Integer getIntQuantity() { return IntQuantity.get(); }
    public LocalDate getDateLent() { return DateLent.get(); }
    public LocalDate getDateDue() { return DateDue.get(); }
    public Boolean getBoolReturned() { return BoolReturned.get(); }
    public Long getIntID() { return LngID.get(); }
    
   // Setters
    public void setDateDue(LocalDate value) { DateDue.set(value); }
    public void setBoolReturned(Boolean value) { BoolReturned.set(value); }
   // Note, ID, device, quantity and datelent are all read only, and so there are no setter for those properties
    
}
