/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package croftventory.Types;

import java.math.BigDecimal;
import javafx.beans.property.*;

/**
 *
 * Defines the Device object
 * 
 * @author kamron
 * 
 */
public class Device {
    // Properties
    // These are used over variables as they can utilize events
    private SimpleStringProperty StrName = new SimpleStringProperty();
    private SimpleIntegerProperty IntQuantity = new SimpleIntegerProperty();
    private SimpleObjectProperty<BigDecimal> DeciValue = new SimpleObjectProperty<>();
    private SimpleIntegerProperty IntID = new SimpleIntegerProperty();
    
    // Initialisers
    // Uses polymorphisem to handle storing and retrieving data from database
    // As ID is generated by database itself (for security reasons)
    public Device(String name, int quantity, BigDecimal value, int ID) {
        this.StrName.set(name);
        this.IntQuantity.set(quantity);
        this.DeciValue.set(value);
        this.IntID.set(ID);
    }

    public Device(String name, int quantity, BigDecimal value) {
        this.StrName.set(name);
        this.IntQuantity.set(quantity);
        this.DeciValue.set(value);
    }
    
    // Getters
    // Getters which return properties
    // Useful for UI elements
    public StringProperty nameProperty() { return StrName; }
    public IntegerProperty QuantityProperty() { return IntQuantity; }
    public ObjectProperty<BigDecimal> ValueProperty() { return DeciValue; }
    public IntegerProperty IDProperty() { return IntID; }
    
    //Getters for variables
    //Useful for validation and other purposes
    public String getStrName() { return StrName.get(); }
    public Integer getIntQuantity() { return IntQuantity.get(); }
    public BigDecimal getDeciValue() { return DeciValue.get(); }
    public Integer getIntID() { return IntID.get(); }
    
   // Setters
   public void setStrName(String value) { StrName.set(value); }
   public void setIntQuantity(int value) { IntQuantity.set(value); }
   public void setDeciValue(BigDecimal value) { DeciValue.set(value); }
   // Note, ID is read only, and so there is no setter for the property
}
