/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Types;

import ObjectManager.StorageController;
import javafx.beans.property.*;
import java.time.LocalDate;

/**
 *
 * Defines the Booking object
 * 
 * @author kamron
 * 
 */

public class Booking {
    // Properties
    // These are used over variables as they can utilize events
    // Additionally they are useful for the TableView
    private SimpleStringProperty Student = new SimpleStringProperty();
    private SimpleLongProperty Device = new SimpleLongProperty();
    private SimpleIntegerProperty Quantity = new SimpleIntegerProperty();
    private SimpleObjectProperty<LocalDate> Lent = new SimpleObjectProperty<>();
    private SimpleObjectProperty<LocalDate> Due = new SimpleObjectProperty<>();
    private SimpleBooleanProperty Returned = new SimpleBooleanProperty();
    private SimpleLongProperty ID = new SimpleLongProperty();
    
    // Property to keep the name of the student and device name (for the TableView)
    // Note although these shouldn't change, they can only be set in the initializer
    private SimpleStringProperty StudentName;
    private SimpleStringProperty DeviceName;
    
    // Initializer
    // Uses polymorphism to handle storing and retrieving data from database
    // As ID is generated by database itself (for security reasons)
    public Booking(String student, long device, int quantity, LocalDate lent, LocalDate due, boolean returned, long id) {
        this.DeviceName = new SimpleStringProperty();
        this.StudentName = new SimpleStringProperty();
        this.Student.set(student);
        this.Device.set(device);
        this.Quantity.set(quantity);
        this.Lent.set(lent);
        this.Due.set(due);
        this.Returned.set(returned);
        this.ID.set(id);
        
        this.StudentName.set(StorageController.getStudent(Student.get()).getName());
        this.DeviceName.set(StorageController.getDevice(Device.get()).getName());
    }
    
    public Booking(String student, long device, int quantity, LocalDate lent, LocalDate due, boolean returned) {
        this.DeviceName = new SimpleStringProperty();
        this.StudentName = new SimpleStringProperty();
        this.Student.set(student);
        this.Device.set(device);
        this.Quantity.set(quantity);
        this.Lent.set(lent);
        this.Due.set(due);
        this.Returned.set(returned);
        
        this.StudentName.set(StorageController.getStudent(Student.get()).getName());
        this.DeviceName.set(StorageController.getDevice(Device.get()).getName());
    }
    
    // Getters
    // Getters which return properties
    // Useful for UI elements
    public StringProperty studentProperty() { return Student; }
    public LongProperty deviceProperty() { return Device; }
    public IntegerProperty quantityProperty() { return Quantity; }
    public ObjectProperty<LocalDate> lentProperty() { return Lent; }
    public ObjectProperty<LocalDate> dueProperty() { return Due; }
    public BooleanProperty returnedProperty() { return Returned; }
    public LongProperty IDProperty() { return ID; }
    public StringProperty studentNameProperty() { return StudentName; }
    public StringProperty deviceNameProperty() { return DeviceName; }
    
    //Getters for variables
    //Useful for validation and other purposes
    public String getStudent() { return Student.get(); }
    public Long getDevice() { return Device.get(); }
    public Integer getQuantity() { return Quantity.get(); }
    public LocalDate getDateLent() { return Lent.get(); }
    public LocalDate getDateDue() { return Due.get(); }
    public Boolean getReturned() { return Returned.get(); }
    public Long getID() { return ID.get(); }
    public String getStudentName() { return StudentName.get(); }
    public String getDeviceName() { return DeviceName.get(); }
    
   // Setters
    public void setDateDue(LocalDate value) { Due.set(value); }
    public void setReturned(Boolean value) { Returned.set(value); }
   // Note, ID, device, quantity and datelent are all read only, and so there are no setter for those properties
    
}
